# permissions to do viewer painters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: painter-viewer-role
rules:
- apiGroups:
  - clusterdepot.k8sland.io
  resources:
  - painters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterdepot.k8sland.io
  resources:
  - painters/status
  verbs:
  - get
