# permissions to do edit painters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: painter-editor-role
rules:
- apiGroups:
  - clusterdepot.k8sland.io
  resources:
  - painters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterdepot.k8sland.io
  resources:
  - painters/status
  verbs:
  - get
  - patch
  - update
