---
apiVersion: v1
kind: Service
metadata:
  name: dictionary
  namespace: istio
spec:
  type: NodePort
  selector:
    app: dictionary
  ports:
    - name: http
      protocol: TCP
      nodePort: 30400
      port: 4000
