apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
      rev: v1
  template:
    metadata:
      labels:
        app: dictionary
        rev: v1
    spec:
      containers:
        - name: dictionary
          image: k8sland/go-dictionary-svc:0.0.3
          imagePullPolicy: IfNotPresent
          args: ["/app/dictionary", "-d", "trump.txt"]
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 50Mi
          ports:
            - name: http
              containerPort: 4000
