---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iconoflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iconoflix
  template:
    metadata:
      labels:
        app: iconoflix
    spec:
      containers:
        - name: iconoflix
          image: quay.io/imhotepio/iconoflix:mem
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 4000
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
            limits:
              cpu: 400m
              memory: 80Mi
          livenessProbe:
            httpGet:
              path: /check/health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /check/alive
              port: api
            initialDelaySeconds: 20
            periodSeconds: 30
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: iconoflix
spec:
  type: NodePort
  selector:
    app: iconoflix
  ports:
    - port: 4000
      nodePort: 30400
