---
# Deployment
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: iconoflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iconoflix
  template:
    metadata:
      labels:
        app: iconoflix
    spec:
      containers:
      - name:            iconoflix
        image:           quay.io/imhotepio/iconoflix:mem
        imagePullPolicy: IfNotPresent
        ports:
        - name:          api
          containerPort: 4000
        resources:
          limits:
            cpu:    100m
            memory: 80Mi
          requests:
            cpu:    50m
            memory: 50Mi
        <YOUR_CODE Define your probes!!>
---
# Service
kind:       Service
apiVersion: v1
metadata:
  name: iconoflix
spec:
  type:  NodePort
  selector:
    app: iconoflix
  ports:
    - port:     4000
      nodePort: 30400