apiVersion: apps/v1
kind:       Deployment
metadata:
  name: dictionary2
  labels:
    app: dictionary2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary2
  template:
    metadata:
      labels:
        app: dictionary2
    spec:
      containers:
      - name: dictionary2
        image: k8sland/go-dictionary-svc:0.0.2
        command: ['/app/dictionary', '-a', '/var/dictionary/words', '-d', 'trick_or_treat.txt']
        ports:
        - name:          http
          containerPort: 4000
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
        resources:
          limits:
            cpu:    100m
            memory: 15Mi
      initContainers:
      - name:    git
        image:   luzhzh/git-client
        command: ['sh', '-c', 'rm -rf /var/dictionary/words && git clone https://github.com/k8sland/dictionaries.git /var/dictionary/words']
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
      volumes:
      - name: dictionary
        hostPath:
          path: /home/docker/dictionary
---
apiVersion: v1
kind:       Service
metadata:
  name: dictionary2
spec:
  type: ClusterIP
  selector:
    app: dictionary2
  ports:
  - name:       http
    port:       4002
    targetPort: http