apiVersion: apps/v1
kind:       Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        !!CHANGE_ME!!
    spec:
      containers:
      - name:            nginx
        image:           nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name:          http
          protocol:      TCP
          containerPort: 80
        resources:
          limits:
            cpu:    100m
            memory: 100Mi