apiVersion: v1
kind:       ServiceAccount
metadata:
  name:      partysched
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRoleBinding
metadata:
  name: partysched
subjects:
- kind:      ServiceAccount
  name:      partysched
  namespace: default
roleRef:
  kind:     ClusterRole
  name:     system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
