apiVersion: v1
kind:       ServiceAccount
metadata:
  name:      !!CHANGE_ME!!
  namespace: !!CHANGE_ME!!

---
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRoleBinding
metadata:
  name: partysched
subjects:
- kind:      ServiceAccount
  name:      !!CHANGE_ME!!
  namespace: !!CHANGE_ME!!
roleRef:
  kind:     ClusterRole
  name:     !!CHANGE_ME!!
  apiGroup: rbac.authorization.k8s.io
