---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: depadm
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: depadm
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: depadm
subjects:
  - kind: ServiceAccount
    name: depadm
    namespace: default
roleRef:
  kind: ClusterRole
  name: depadm
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depadm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depadm
  template:
    metadata:
      labels:
        app: depadm
    spec:
      serviceAccount: depadm
      containers:
        - name: depadm
          image: k8sland/go-depadm:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 443
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: depadm
spec:
  type: NodePort
  selector:
    app: depadm
  ports:
    - name: https
      protocol: TCP
      nodePort: 30443
      port: 443
      targetPort: http
