
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: freds.blee.k8sland.io
spec:
  group: blee.k8sland.io
  names:
    kind: Fred
    plural: freds
  scope: ""
  validation:
    openAPIV3Schema:
      description: Fred is the Schema for the freds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FredSpec defines the desired state of Fred
          properties:
            foo:
              description: Foo is an example field of Fred. Edit Fred_types.go to
                remove/update
              type: string
          type: object
        status:
          description: FredStatus defines the observed state of Fred
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
