# permissions to do edit freds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fred-editor-role
rules:
- apiGroups:
  - blee.k8sland.io
  resources:
  - freds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blee.k8sland.io
  resources:
  - freds/status
  verbs:
  - get
  - patch
  - update
