# permissions to do viewer freds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fred-viewer-role
rules:
- apiGroups:
  - blee.k8sland.io
  resources:
  - freds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blee.k8sland.io
  resources:
  - freds/status
  verbs:
  - get
