apiVersion: networking.istio.io/v1alpha3
kind:       VirtualService
metadata:
  name: mirror
spec:
  hosts:
    - dictionary
  http:
  - route:
    - destination:
        host:   dictionary
        subset: v1
      weight: 100
    mirror:
      host:   dictionary
      subset: v2