apiVersion: networking.istio.io/v1alpha3
kind:       DestinationRule
metadata:
  name: dictionary
spec:
  host: dictionary
  subsets:
  - name: v1
    labels:
      app: dictionary
      rev: v1
  - name: v2
    labels:
      app: dictionary
      rev: v2