
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: painters.clusterdepot.k8sland.io
spec:
  group: clusterdepot.k8sland.io
  names:
    kind: Painter
    plural: painters
    shortNames:
    - pt
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Painter is the Schema for the painters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PainterSpec defines the desired state of Painter
          properties:
            color:
              enum:
              - Red
              - Blue
              - Green
              type: string
          type: object
        status:
          description: PainterStatus defines the observed state of Painter
          properties:
            paintedPods:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
